name: Validate Guide
on:
  pull_request:
    branches: master
    paths: content/gtnh/guides/**
jobs:
  run_lint:
    name: Run Lint
    runs-on: ubuntu-slim
    permissions:
      pull-requests: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures we have the full history for diff
      - name: Get changed files
        id: changes
        run: |
          git fetch origin ${{ github.base_ref }}
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep 'content/')
          echo "changed=$CHANGED_FILES" >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: npm i -g markdownlint-cli

      - name: Run lint
        id: lint
        continue-on-error: true
        run: |
          echo "errors<<EOF" >> $GITHUB_OUTPUT
          markdownlint -r lint/index.cjs '${{ steps.changes.outputs.changed }}' &>> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Process Results
        id: process
        run: |
          echo "${{ steps.lint.outputs.errors }}" >> errors.txt
          cat errors.txt
          if [[ $(cat errors.txt | wc -l) -ne 1 ]]; then
            echo "message<<EOF" >> $GITHUB_OUTPUT
            echo "HV to MV, yes." >> $GITHUB_OUTPUT
            echo "The following errors were reported:" >> $GITHUB_OUTPUT
            echo "$errors" >> $GITHUB_OUTPUT
            echo 'EOF' >> $GITHUB_OUTPUT
          else
            echo "message<<EOF" >> $GITHUB_OUTPUT
            echo "There were no deaths, no skill issues, not a single problem." >> $GITHUB_OUTPUT
            echo "No errors reported for the guide" >> $GITHUB_OUTPUT
            echo 'EOF' >> $GITHUB_OUTPUT
          fi
      - name: Publish to PR
        uses: mshick/add-pr-comment@v2
        with:
          message: ${{ steps.process.outputs.message}}

